authentication/urls.py
from django.conf.urls import url
from authentication.views import (
    LoginAuthView,
    LogoutAuthView,
    PasswordChangeAuthView,
    PasswordChangeDoneAuthView,
    PasswordResetAuthView,
    PasswordResetConfirmAuthView,
    PasswordResetDoneAuthView,
    PasswordResetCompleteAuthView
)


urlpatterns = [
    url(r'^change_password_done', PasswordChangeDoneAuthView.as_view(), name='change_password_done'),
    url(r'^change_password', PasswordChangeAuthView.as_view(), name='change_password'),
    url(r'^login', LoginAuthView.as_view(), name='login'),
    url(r'^logout', LogoutAuthView.as_view(), name='logout'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmAuthView.as_view(),
        name='password_reset_confirm'
        ),
    url(r'^password_reset_complete', PasswordResetCompleteAuthView.as_view(), name='password_reset_complete'),
    url(r'^password_reset_done', PasswordResetDoneAuthView.as_view(), name='password_reset_done'),
    url(r'^password_reset', PasswordResetAuthView.as_view(), name='password_reset'),
]

supportHub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('authentication.urls', namespace='auth')),
    url(r'^search_text/', include('haystack.urls')),
    url(r'^', include('ticket.urls', namespace='ticket')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)),] + urlpatterns

ticket/urls.py
from django.conf.urls import url
from ticket.views import (
    CommentCreateView,
    CommentDeleteView,
    EmailSubscriberCreateView,
    EmailSubscriberDeleteView,
    SubscriberAddView,
    SubscriberDeleteView,
    SubscriberCreateView,
    SubscriberListView,
    TagCreateAndAddView,
    TagRemoveFromTicketView,
    TicketCreateView,
    TicketDeleteView,
    TicketMergeView,
    ticket_multi_delete_view,
    ticket_multi_merge_view,
    ticket_multi_select_view,
    TicketListView,
    TicketQuickSearchView,
    TicketReportingView,
    TicketSearchView,
    TicketUpdateView
)

urlpatterns = [
    url(r'^$', TicketListView.as_view(), name='ticket_list'),
    url(r'^comment/create$', CommentCreateView.as_view(), name='create_comment'),
    url(r'^comment/(?P<id>[-\w]+)/delete$', CommentDeleteView.as_view(), name='delete_comment'),
    url(r'^create$', TicketCreateView.as_view(), name='create_ticket'),
    url(r'^email_subscriber/create$', EmailSubscriberCreateView.as_view(), name='create_email_subscriber'),
    url(r'^email_subscriber/(?P<id>[-\w]+)/delete$', EmailSubscriberDeleteView.as_view(), name='delete_email_subscriber'),
    url(r'^multi_delete$', ticket_multi_delete_view, name='multi_delete'),
    url(r'^multi_merge$', ticket_multi_merge_view, name='multi_merge'),
    url(r'^multi_select$', ticket_multi_select_view, name='multi_select'),
    url(r'^quick_search$', TicketQuickSearchView.as_view(), name='ticket_quick_search'),
    url(r'^reporting$', TicketReportingView.as_view(), name='ticket_reporting'),
    url(r'^search', TicketSearchView.as_view(), name='ticket_search'),
    url(r'^subscriber/(?P<user_id>[-\w]+)/(?P<ticket_id>[-\w]+)/add$', SubscriberAddView.as_view(), name='add_subscriber'),
    url(r'^subscriber/(?P<user_id>[-\w]+)/(?P<ticket_id>[-\w]+)/delete', SubscriberDeleteView.as_view(), name='delete_subscriber'),
    url(r'^subscriber/create$', SubscriberCreateView.as_view(), name='create_subscriber'),
    url(r'^tag/create$', TagCreateAndAddView.as_view(), name='create_tag'),
    url(r'^tag/(?P<tag_id>[-\w]+)/(?P<ticket_id>[-\w]+)/remove$', TagRemoveFromTicketView.as_view(), name='remove_tag'),
    url(r'^(?P<id>[-\w]+)/delete$', TicketDeleteView.as_view(), name='delete_ticket'),
    url(r'^(?P<id>[-\w]+)/merge$', TicketMergeView.as_view(), name='merge_ticket'),
    url(r'^(?P<id>[-\w]+)/update$', TicketUpdateView.as_view(), name='update_ticket'),
    url(r'^(?P<id>[-\w]+)/subscribers$', SubscriberListView.as_view(), name='subscriber_list'),
]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block head_title %}Support Hub{% endblock %}</title>
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
              integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
              crossorigin="anonymous">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
              rel="stylesheet"
              integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
              crossorigin="anonymous">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript">
            google.load("visualization", "1", {packages:["corechart"]});
        </script>
    </head>
    <body>
        <nav class="navbar navbar-light navbar-toggleable-sm bg-faded justify-content-center">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#collapsingNavbar3">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a href='{% url "ticket:ticket_list" %}' class="navbar-brand d-flex w-100 mr-auto">
                <img src="http://2db.com/images/2db_logo.jpg" height="30" class="d-inline-block align-top" alt="">
            </a>

            {% if user.is_authenticated %}
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav mx-auto w-100 justify-content-center">
                        <li class="nav-item">
                            <form class="form-inline" method="get" action='{% url "ticket:ticket_quick_search" %}'>
                                <input class="form-control mr-sm-2" type="text" name="ticket_id" placeholder="Search Ticket ID">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                            </form>
                        </li>
                    </ul>
                </div>

                <div class="navbar-collapse collapse" id="collapsingNavbar3">
                    <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link" href='{% url "ticket:ticket_list" %}'>Tickets</a>
                        </li>
                        {% if user.profile.is_twodb_user %}
                            <li class="nav-item">
                                <a class="nav-link" href='{% url "ticket:ticket_search" %}'>Search</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/admin">Admin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href='{% url "ticket:ticket_reporting" %}'>Reporting</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href='{% url "auth:change_password" %}'>Change Password</a>
                        </li>

    {#                    <li class="nav-item dropdown">#}
    {#                        <a class="nav-link dropdown-toggle"#}
    {#                           href="http://example.com"#}
    {#                           id="navbarDropdownMenuLink"#}
    {#                           data-toggle="dropdown" a#}
    {#                           ria-haspopup="true"#}
    {#                           aria-expanded="false"> Profile#}
    {#                        </a>#}
    {#                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">#}
    {#                          <a class="dropdown-item" href="#">Action</a>#}
    {#                          <a class="dropdown-item" href="#">Another action</a>#}
    {#                          <a class="dropdown-item" href="#">Something else here</a>#}
    {#                        </div>#}
    {#                    </li>#}
                        <li class="nav-item">
                            <a class="nav-link" href='{% url "auth:logout" %}'>Logout: {{ user.username }}</a>
                        </li>
                    </ul>

                </div>
            {% endif %}
        </nav>

        <div class="container-fluid">

            {% block content %}
                No Content found
            {% endblock content %}

            {% if messages %}
                <br>
                <div class="row justify-content-lg-center">
                    <div class="col-lg-4">
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                    <div class="alert alert-info alert-dismissible text-center fade show">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        {{ message }}
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}

        </div>

        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.pie.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.time.min.js"></script>

        <script>
            $( function() {
                $("select").each(function(){
                    $(this).change(function() {
                        $("#id_form_filter").submit();
                    });
                });

                $( "#id_created_0" ).datepicker();
                $( "#id_created_1" ).datepicker();
                $( "#id_updated_0" ).datepicker();
                $( "#id_updated_1" ).datepicker();
                $( "#id_from_date" ).datepicker();
                $( "#id_to_date" ).datepicker();
                }
            );
        </script>
    </body>
</html>